"""empty message

Revision ID: 1760dc3ae8b4
Revises: 3e96f370ce06
Create Date: 2024-05-07 13:32:40.190852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1760dc3ae8b4'
down_revision = '3e96f370ce06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
