"""empty message

Revision ID: 18304c607124
Revises: f6ac8c17a7c2
Create Date: 2024-05-06 11:49:52.254907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18304c607124'
down_revision = 'f6ac8c17a7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('cedula', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
