"""empty message

Revision ID: 1a1174a5d664
Revises: 4256a8cf5bcd
Create Date: 2024-05-09 14:36:40.269702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1174a5d664'
down_revision = '4256a8cf5bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('ci', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitante')
    # ### end Alembic commands ###
