"""empty message

Revision ID: 1e41fc7990c9
Revises: f42369a435f0
Create Date: 2024-05-03 13:49:51.384824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e41fc7990c9'
down_revision = 'f42369a435f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamento', schema=None) as batch_op:
        batch_op.drop_column('solicitud')

    # ### end Alembic commands ###
