"""empty message

Revision ID: 2543573328ba
Revises: 5b08ed5b4c60
Create Date: 2024-05-06 15:26:41.212359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2543573328ba'
down_revision = '5b08ed5b4c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('empresa_numero_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitud', ['solicitud_id'], ['id'])
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('empresa_numero_fkey', 'solicitud', ['numero'], ['id'])
        batch_op.drop_column('solicitud_id')

    # ### end Alembic commands ###
