"""empty message

Revision ID: 25446e645dbe
Revises: da426c7d5c9b
Create Date: 2024-05-20 11:45:59.820632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25446e645dbe'
down_revision = 'da426c7d5c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###
