"""empty message

Revision ID: 4256a8cf5bcd
Revises: 5ccaa62da45f
Create Date: 2024-05-09 13:45:17.372528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4256a8cf5bcd'
down_revision = '5ccaa62da45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('direc', sa.String(length=50), nullable=True),
    sa.Column('telf', sa.String(length=50), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
