"""empty message

Revision ID: 59fa3f2f223c
Revises: 89c015490eae
Create Date: 2024-05-07 09:21:07.224347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fa3f2f223c'
down_revision = '89c015490eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_solicitud_id_fkey', type_='foreignkey')
        batch_op.drop_column('solicitud_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('empresa_solicitud_id_fkey', 'solicitud', ['solicitud_id'], ['id'])

    # ### end Alembic commands ###
