"""empty message

Revision ID: 67286c184d5a
Revises: 24b93b66da2f
Create Date: 2024-06-15 11:04:52.244782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67286c184d5a'
down_revision = '24b93b66da2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('direc', sa.String(length=50), nullable=True),
    sa.Column('telf', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('ci', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('firmante', sa.String(length=50), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('responsable', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['solicitante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('cedula', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('username')
    )
    op.create_table('asginar_departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('asignar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depertamento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['depertamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignar')
    op.drop_table('asginar_departamento')
    op.drop_table('usuario')
    op.drop_table('solicitud')
    op.drop_table('solicitante')
    op.drop_table('empresa')
    op.drop_table('departamento')
    # ### end Alembic commands ###
