"""empty message

Revision ID: 93efae252f2b
Revises: 59fa3f2f223c
Create Date: 2024-05-07 11:20:21.084998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93efae252f2b'
down_revision = '59fa3f2f223c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cedula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
