"""empty message

Revision ID: 9e04ec345f4e
Revises: 4b30684f6607
Create Date: 2024-05-06 10:05:09.855783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e04ec345f4e'
down_revision = '4b30684f6607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('firmante', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Solicitud')
    # ### end Alembic commands ###
