"""empty message

Revision ID: 9efd0421d329
Revises: 2543573328ba
Create Date: 2024-05-06 15:28:04.157580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efd0421d329'
down_revision = '2543573328ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_solicitud_id_fkey', type_='foreignkey')
        batch_op.drop_column('solicitud_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('empresa_solicitud_id_fkey', 'solicitud', ['solicitud_id'], ['id'])

    # ### end Alembic commands ###
