"""empty message

Revision ID: a37c8bc7e956
Revises: ac1d89112a22
Create Date: 2024-06-14 09:16:33.542381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37c8bc7e956'
down_revision = 'ac1d89112a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=100), nullable=True))

    with op.batch_alter_table('solicitante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['telefono'])

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numero'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('solicitante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('asignar', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
