"""empty message

Revision ID: ac1d89112a22
Revises: b8f7111c632f
Create Date: 2024-05-31 14:31:41.393752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1d89112a22'
down_revision = 'b8f7111c632f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['telefono'])

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numero'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('solicitante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
