"""empty message

Revision ID: bb04120f12e8
Revises: 1a1174a5d664
Create Date: 2024-05-09 14:43:58.042067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb04120f12e8'
down_revision = '1a1174a5d664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('ci', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_solicitud_id_fkey', type_='foreignkey')
        batch_op.drop_column('solicitud_id')

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitante', ['solicitante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('solicitante_id')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('empresa_solicitud_id_fkey', 'solicitud', ['solicitud_id'], ['id'])

    op.drop_table('solicitante')
    # ### end Alembic commands ###
