"""empty message

Revision ID: c93103454e4f
Revises: 9c6d26e4d549
Create Date: 2024-05-13 11:53:08.192622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93103454e4f'
down_revision = '9c6d26e4d549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depertamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departamento', ['depertamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('depertamento_id')

    # ### end Alembic commands ###
