"""empty message

Revision ID: f42369a435f0
Revises: 
Create Date: 2024-05-03 12:05:33.458152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42369a435f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=250), nullable=True),
    sa.Column('jefe', sa.String(length=250), nullable=True),
    sa.Column('documento', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('firmante', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('solicitud', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    op.drop_table('departamento')
    # ### end Alembic commands ###
