"""empty message

Revision ID: f6ac8c17a7c2
Revises: f8112c692d4b
Create Date: 2024-05-06 11:06:58.021314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ac8c17a7c2'
down_revision = 'f8112c692d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('direc', sa.String(length=50), nullable=True),
    sa.Column('telf', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numero'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
