"""empty message

Revision ID: f8112c692d4b
Revises: 9e04ec345f4e
Create Date: 2024-05-06 10:07:27.102422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8112c692d4b'
down_revision = '9e04ec345f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('firmante', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Solicitud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Solicitud',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Solicitud_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firmante', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Solicitud_pkey')
    )
    op.drop_table('solicitud')
    # ### end Alembic commands ###
